#!/bin/sh

IPTABLESLIB=@libdir@/iptables
cd ${IPTABLESLIB}/ptest || exit 1

LOG="${IPTABLESLIB}/ptest/iptables_ptest_$(date +%Y%m%d-%H%M%S).log"
iptables/tests/shell/run-tests.sh 2>&1 | sed -E '/I: \[OK\]/ s/^/PASS: / ; /W: \[FAILED\]/ s/^/FAIL: /' | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g" | tee -a "${LOG}"

passed=$(grep -c PASS: "${LOG}")
failed=$(grep -c FAIL: "${LOG}")
all=$((passed + failed))

(   echo "=== Test Summary ==="
    echo "TOTAL: ${all}"
    echo "PASSED: ${passed}"
    echo "FAILED: ${failed}"
) | tee -a "${LOG}"
